### ISSUE TITLE
NPM package name rights

### ISSUE THREAD

**Issue by zivkovicmilos** [ucsd-cse112-sp19/team7#60]
Hello!

I'm not really sure who I should contact about this specifically, so I'm opening up an issue in the hopes that one of the maintainers will see it.

I am the author of the [pandoras-box](https://github.com/madz-lab/pandoras-box), a small CLI tool that lets you spin up a stress testing environment for Ethereum-compatible blockchain networks (geth, hyperledger besu...). When developing the tooling, I've always had an open source permissive license in mind - Apache 2.

The CLI tool itself is a simple TypeScript app, so it only made sense to publish it to NPM.
When I went to publish it, I found out there was already a [pandoras-box](https://www.npmjs.com/package/pandoras-box) package on NPM, that redirects back to this repo.

Judging by the repo and package activity, it doesn't seem to be active for a while now.

What I wanted to ask was - would anyone maintaining this npm package be willing to let me use the `pandoras-box` package name for my open source project?

I've currently published the package under the [@madz-lab/pandoras-box](https://www.npmjs.com/package/@madz-lab/pandoras-box) package name.

Thank you for the consideration, I'll answer any questions you may have.

**Comment by ericsaliu** [comment]
Hi Miloš,

I have no issues releasing the pandoras-box to you for your tool; it sounds interesting and useful! Unfortunately I am unfamiliar with package management and believe @cortezpage was the original publisher. Let’s give him a few days to see this issue and we’ll go from there.

**Comment by cortezpage** [comment]
Unfortunately, I can no longer receive email to my university email account associated with my npm account, so I can't login to npm.

**Comment by zivkovicmilos** [comment]
@cortezpage 

Thank you for replying on such short notice.

That's a bummer to hear. Have you tried opening up a ticket with NPM? They have procedures in place for users who cannot access emails associated with their accounts:
https://docs.npmjs.com/receiving-a-one-time-password-over-email#unable-to-access-email

**Comment by cortezpage** [comment]
I just opened up a ticket with NPM to try to regain account access.

**Comment by cortezpage** [comment]
I regained account access and deleted the pandoras-box package.

**Comment by ericsaliu** [comment]
@zivkovicmilos I’m closing this issue. Good luck with your package!

**Comment by zivkovicmilos** [comment]
Thank you @cortezpage 🙏 

It may be a small gesture for you, but it means a lot to me, and the team behind pandoras-box
